accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import SignUpView

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy

from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    AccountCreateView,
    AccountListView,
    ExpenseCategoryCreateView,
    ExpenseCategoryListView,
    ReceiptCreateView,
    ReceiptListView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from pickle import TRUE
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField(blank=True, null=True)
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
        null=TRUE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/forms.py
# from django import forms
# from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserCreationForm
# from django.core.exceptions import ValidationError
# from django.forms.fields import EmailField
# from django.forms.forms import Form


# class SignUpForm(UserCreationForm):
#     username = forms.CharField(label="Username", min_length=5, max_length=150)
#     password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
#     password2 = forms.CharField(
#         label="Confirm password", widget=forms.PasswordInput
#     )

#     def username_clean(self):
#         username = self.cleaned_data["username"].lower()
#         new = User.objects.filter(username=username)

#         if new.count():
#             raise ValidationError("User Already Exist")
#         return username

#     def clean_password2(self):
#         password1 = self.cleaned_data["password1"]
#         password2 = self.cleaned_data["password2"]

#         if password1 and password2 and password1 != password2:
#             raise ValidationError("Passwords don't match")
#         return password2

#     def save(self, commit=True):
#         user = User.objects.create_user(
#             self.cleaned_data["username"], self.cleaned_data["password1"]
#         )
#         return user

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# from .forms import SignUpForm


# Create your views here.
def SignUpView(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")

    else:
        form = UserCreationForm()

    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from re import L
from django.shortcuts import render, redirect

from receipts.models import Account, ExpenseCategory, Receipt

from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")

    def get_form(self, *args, **kwargs):
        form = super(ReceiptCreateView, self).get_form(*args, **kwargs)

        form.fields["category"].queryset = ExpenseCategory.objects.filter(
            owner=self.request.user
        )
        form.fields["account"].queryset = Account.objects.filter(
            owner=self.request.user
        )
        return form


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "receipts/categories.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "receipts/accounts.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/create_category.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/create_account.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_accounts")

receipts/templates/receipts/accounts.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Accounts</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li>
                            <a href="{% url 'home' %}">Receipts</a>
                        </li>
                        <li>
                            <a href="{% url 'list_categories' %}">Categories</a>
                        </li>
                        <li>
                            <a href="{% url 'list_accounts' %}">Accounts</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <h1>Accounts</h1>
            <p>
                <a href="{% url 'create_account' %}">Create</a>
            </p>
            <table>
                <thead>
                    <tr>
                        <td>Name</td>
                        <td>Number</td>
                        <td>Number of recipts</td>
                    </tr>
                </thead>
                <tbody>
                    {% for account in account_list %}
                        <tr>
                            <td>{{ account.name }}</td>
                            <td>{{ account.number }}</td>
                            <td>{{ account.receipts.all | length }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </body>
</html>

receipts/templates/receipts/categories.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Expense Categories</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li>
                            <a href="{% url 'home' %}">Receipts</a>
                        </li>
                        <li>
                            <a href="{% url 'list_categories' %}">Categories</a>
                        </li>
                        <li>
                            <a href="{% url 'list_accounts' %}">Accounts</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <h1>Expense Categories</h1>
            <p>
                <a href="{% url 'create_category' %}">Create</a>
            </p>
            <table>
                <thead>
                    <tr>
                        <td>Name</td>
                        <td>Number of receipts</td>
                    </tr>
                </thead>
                <tbody>
                    {% for category in expensecategory_list %}
                        <tr>
                            <td>{{ category.name }}</td>
                            <td>{{ category.receipts.all | length }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </body>
</html>

receipts/templates/receipts/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li>
                            <a href="{% url 'home' %}">Receipts</a>
                        </li>
                        <li>
                            <a href="{% url 'list_categories' %}">Categories</a>
                        </li>
                        <li>
                            <a href="{% url 'list_accounts' %}">Accounts</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Create Receipt</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/receipts/create_account.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create Account</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li>
                            <a href="{% url 'home' %}">Receipts</a>
                        </li>
                        <li>
                            <a href="{% url 'list_categories' %}">Categories</a>
                        </li>
                        <li>
                            <a href="{% url 'list_accounts' %}">Accounts</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Create Account</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/receipts/create_category.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create Category</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li>
                            <a href="{% url 'home' %}">Receipts</a>
                        </li>
                        <li>
                            <a href="{% url 'list_categories' %}">Categories</a>
                        </li>
                        <li>
                            <a href="{% url 'list_accounts' %}">Accounts</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Create Category</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/receipts/list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li>
                            <a href="{% url 'home' %}">Receipts</a>
                        </li>
                        <li>
                            <a href="{% url 'list_categories' %}">Categories</a>
                        </li>
                        <li>
                            <a href="{% url 'list_accounts' %}">Accounts</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url 'signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <h1>My Receipts</h1>
            <p>
                <a href="{% url 'create_receipt' %}">Create</a>
            </p>
            <table>
                <thead>
                    <tr>
                        <td>Vendor</td>
                        <td>Total</td>
                        <td>Tax</td>
                        <td>Date</td>
                        <td>Category</td>
                        <td>Account</td>
                    </tr>
                </thead>
                <tbody>
                    {% for receipt in receipt_list %}
                        <tr>
                            <td>{{ receipt.total }}</td>
                            <td>{{ receipt.vendor }}</td>
                            <td>{{ receipt.tax }}</td>
                            <td>{{ receipt.date|date:"m-d-Y" }}</td>
                            <td>{{ receipt.category }}</td>
                            <td>{{ receipt.account }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </main>
    </body>
</html>